# Generated by Django 4.0.4 on 2022-11-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
